# Schema for the configuration files of the Config Entity Example module.

# This schema tells the config system how to read our config YML files.
# See for example the file config/meteor.server.marvin.yml, which
# contains our default config entity.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

meteor.meteor_server.*:
  type: mapping
  label: 'Server'
  mapping:
    id:
      type: string
      label: 'Server id'
    uuid:
      type: string
      label: 'UUID'
    label:
      type: label
      label: 'Label'
    appKey:
      type: string
      label: 'Application Key'
    langcode:
      type: string
      label: 'Default language'
